// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstMillionAPI.Infrastructure.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFirstMillionAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715080739_AddAccountCardFields")]
    partial class AddAccountCardFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<int?>("BillingDueDay")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludeInTotal")
                        .HasColumnType("boolean");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(7087),
                            Icon = "home",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Moradia",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8178),
                            Icon = "restaurant",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Alimentação",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#EAB308",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8182),
                            Icon = "directions_car",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Transporte",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#22C55E",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8194),
                            Icon = "health_and_safety",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Saúde",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8195),
                            Icon = "school",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Educação",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8201),
                            Icon = "sports_esports",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Lazer",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#EC4899",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8214),
                            Icon = "shopping_bag",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Compras",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6B7280",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8216),
                            Icon = "account_balance",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Financeiro",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#14B8A6",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8218),
                            Icon = "subscriptions",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Assinaturas",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8220),
                            Icon = "spa",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Cuidados Pessoais",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#9CA3AF",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8221),
                            Icon = "more_horiz",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Outros (Despesa)",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8223),
                            Icon = "home",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Aluguel",
                            ParentCategoryId = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8383),
                            Icon = "apartment",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Financiamento",
                            ParentCategoryId = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 14,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8384),
                            Icon = "domain",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Condomínio",
                            ParentCategoryId = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 15,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8386),
                            Icon = "bolt",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Água/Luz/Gás",
                            ParentCategoryId = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 16,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8388),
                            Icon = "handyman",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Manutenção",
                            ParentCategoryId = 1,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 17,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8389),
                            Icon = "local_grocery_store",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Supermercado",
                            ParentCategoryId = 2,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 18,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8392),
                            Icon = "restaurant",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Restaurante",
                            ParentCategoryId = 2,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 19,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8393),
                            Icon = "delivery_dining",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Delivery",
                            ParentCategoryId = 2,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 20,
                            Color = "#F97316",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8395),
                            Icon = "local_cafe",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Padaria/Café",
                            ParentCategoryId = 2,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 21,
                            Color = "#EAB308",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8396),
                            Icon = "local_gas_station",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Combustível",
                            ParentCategoryId = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 22,
                            Color = "#EAB308",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8398),
                            Icon = "directions_bus",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Transporte Público",
                            ParentCategoryId = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 23,
                            Color = "#EAB308",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8399),
                            Icon = "local_taxi",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Aplicativo (Uber/99)",
                            ParentCategoryId = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 24,
                            Color = "#EAB308",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8401),
                            Icon = "build",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Manutenção Veículo",
                            ParentCategoryId = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 25,
                            Color = "#EAB308",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8402),
                            Icon = "local_parking",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Estacionamento/Pedágio",
                            ParentCategoryId = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 26,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8404),
                            Icon = "payments",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Salário",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 27,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8405),
                            Icon = "work",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Freela/Autônomo",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 28,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8406),
                            Icon = "trending_up",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Rendimentos",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 29,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8408),
                            Icon = "real_estate_agent",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Aluguel Recebido",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 30,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8409),
                            Icon = "storefront",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Negócios",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 31,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8410),
                            Icon = "card_giftcard",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Presente/Doação",
                            Type = "Income"
                        },
                        new
                        {
                            Id = 32,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2026, 7, 15, 8, 7, 38, 915, DateTimeKind.Utc).AddTicks(8412),
                            Icon = "more_horiz",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Outros (Receita)",
                            Type = "Income"
                        });
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.FinancialGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("ExpectedReturnRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InitialAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialGoals");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.GoalContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalContributions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecurringTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int?>("TotalInstallments")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecurringTransactionId");

                    b.HasIndex("UserId", "CategoryId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Account", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Budget", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Category", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.FinancialGoal", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.User", "User")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.GoalContribution", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.FinancialGoal", "Goal")
                        .WithMany("Contributions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.RecurringTransaction", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.Category", "Category")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.User", "User")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("MyFirstMillionAPI.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.RecurringTransaction", "RecurringTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFirstMillionAPI.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("RecurringTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("RecurringTransactions");

                    b.Navigation("SubCategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.FinancialGoal", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.RecurringTransaction", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyFirstMillionAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("FinancialGoals");

                    b.Navigation("RecurringTransactions");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
